"""Generate an ASCII-art portrait for the site from a photo.

Usage:
    python scripts/ascii_portrait.py <photo> [cols]

Writes src/data/asciiPortrait.js and a preview PNG next to this script.
Requires: pillow, rembg (pip install pillow rembg onnxruntime).
"""

import sys
from pathlib import Path

from PIL import Image, ImageEnhance, ImageFilter, ImageOps
from rembg import remove

# Dark-background ramp: space = empty, dense glyphs = bright.
RAMP = " .':;i1tfLCG08@"
CHAR_ASPECT = 0.52  # mono char width/height ratio; rows get squashed by this

REPO = Path(__file__).resolve().parent.parent
OUT_JS = REPO / "src" / "data" / "asciiPortrait.js"
OUT_PREVIEW = Path(__file__).resolve().parent / "ascii_preview.png"


def to_ascii(photo_path: str, cols: int = 92) -> str:
    img = Image.open(photo_path)
    img = ImageOps.exif_transpose(img)

    # Isolate the subject; background becomes transparent.
    cut = remove(img)

    # Tight-crop to the subject, keep head + top of shoulders.
    bbox = cut.getbbox()
    cut = cut.crop(bbox)
    cut = cut.crop((0, 0, cut.width, int(cut.height * 0.52)))
    bbox = cut.getbbox()
    cut = cut.crop(bbox)

    alpha = cut.getchannel("A")
    gray = cut.convert("L")
    gray = ImageOps.autocontrast(gray, cutoff=1)
    # Gamma-down pulls bright flat skin into mid glyphs so dark features
    # (eyes, beard, hair) stay separated instead of everything hitting '@'.
    gray = gray.point(lambda v: int(255 * (v / 255) ** 1.7))
    gray = gray.filter(ImageFilter.UnsharpMask(radius=5, percent=110, threshold=2))

    rows = int(cut.height / cut.width * cols * CHAR_ASPECT)
    gray = gray.resize((cols, rows), Image.Resampling.LANCZOS)
    alpha = alpha.resize((cols, rows), Image.Resampling.LANCZOS)

    g = gray.load()
    a = alpha.load()
    lines = []
    for y in range(rows):
        line = []
        for x in range(cols):
            if a[x, y] < 96:
                line.append(" ")
            else:
                line.append(RAMP[min(int(g[x, y] / 256 * len(RAMP)), len(RAMP) - 1)])
        lines.append("".join(line).rstrip())
    # Drop fully blank leading/trailing rows.
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines)


def write_js(art: str) -> None:
    assert "`" not in art and "\\" not in art and "${" not in art
    OUT_JS.write_text(
        "// Generated by scripts/ascii_portrait.py — do not edit by hand.\n"
        f"export const ASCII_PORTRAIT = `\n{art}\n`;\n",
        encoding="utf-8",
    )


def write_preview(art: str) -> None:
    from PIL import ImageDraw, ImageFont

    try:
        font = ImageFont.truetype("consola.ttf", 12)
        cw, ch = 7, 14
    except OSError:
        font = ImageFont.load_default()
        cw, ch = 6, 11
    lines = art.split("\n")
    img = Image.new("RGB", (max(len(l) for l in lines) * cw + 20, len(lines) * ch + 20), "#0a0a0d")
    draw = ImageDraw.Draw(img)
    for i, line in enumerate(lines):
        draw.text((10, 10 + i * ch), line, fill="#d9d9e0", font=font)
    img.save(OUT_PREVIEW)


if __name__ == "__main__":
    photo = sys.argv[1]
    cols = int(sys.argv[2]) if len(sys.argv) > 2 else 92
    art = to_ascii(photo, cols)
    write_js(art)
    write_preview(art)
    print(f"{len(art.splitlines())} rows x {cols} cols -> {OUT_JS}")
